config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/recipes')
  get    '/recipes'           => 'recipes#index'

  get    '/recipes/new'       => 'recipes#new', as: 'new_recipe'
  get    '/recipes/:id/edit'  => 'recipes#edit', as: 'edit_recipe'
  get    '/recipes/:id'       => 'recipes#show', as: 'recipe'

  post   '/recipes'           => 'recipes#create'
  patch  '/recipes/:id'       => 'recipes#update'
  put    '/recipes/:id'       => 'recipes#update'

  delete '/recipes/:id'       => 'recipes#destroy'

  get    '/ideas'           => 'ideas#index'

  get    '/ideas/new'       => 'ideas#new', as: 'new_idea'
  get    '/ideas/:id/edit'  => 'ideas#edit', as: 'edit_idea'
  get    '/ideas/:id'       => 'ideas#show', as: 'idea'

  post   '/ideas'           => 'ideas#create'
  patch  '/ideas/:id'       => 'ideas#update'
  put    '/ideas/:id'       => 'ideas#update'

  delete '/ideas/:id'       => 'ideas#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
    render 'index'
  end
  def show
    @idea = Idea.find(params[:id])
    render 'show'
  end
  def new
    @idea = Idea.new
    render 'new'
  end
  def edit
    @idea = Idea.find(params[:id])
    render 'edit'
  end
  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def idea_params
    params.require(:idea).permit(:name, :description, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    render 'index'
  end
  def show
    @recipe = Recipe.find(params[:id])
    render 'show'
  end
  def new
    @recipe = Recipe.new
    render 'new'
  end
  def edit
    @recipe = Recipe.find(params[:id])
    render 'edit'
  end
  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def recipe_params
    params.require(:recipe).permit(:course, :name, :description, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :idea_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :idea_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :idea_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgirls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='container'>
    <div class='navbar-header'>
      <a class='navbar-brand' href='/'>The Recipe app</a>
    </div>
    <ul class='nav navbar-nav'>
      <li>
        <a href='/recipes'>Recipes</a>
      </li>
      <li>
        <a href='/pages/info'>About me</a>
      </li>
    </ul>
  </div>
</nav>
    <div class='container'>
  <%= yield %>
</div>
  <footer>
    <div class='container'>
      Rails Girls 2017
    </div>
  </footer>
  </body>
</html>

app/views/pages/info.html.erb
<h1>About me</h1>
<h2>Welcome to my recipe page!
<%= image_tag("smiley.png",class: :smiley)%></h2>
 <div class="content">If you have a favourite recipe you'd like to add to this page, please get in contact and I'll be happy to add it! </div>
 <div class="author">Author: Marie-Louise Dahl, Stockholm, 2017 </div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course, id: :recipe_course %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :recipe_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :recipe_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :recipe_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.sort_by(&:name).each do |recipe| %>
      <tr>
        <td><%= recipe.course %></td>
        <td><%= link_to recipe.name, recipe %></td>
        <td><%= recipe.description %></td>
        <td><%= image_tag(recipe.picture_url) if recipe.picture.present? %></td>
        <td><%= link_to image_tag("https://image.flaticon.com/icons/svg/61/61456.svg",class:"icon_edit"), edit_recipe_path(recipe) %></td>
        <td><%= link_to image_tag("https://cdn1.iconfinder.com/data/icons/web-ui-2/16/UI_Icons_Outline-28-512.png",class:"icon_trashbin"), recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @recipe.name %>
</h1>
<div class="show_course">
  <%= @recipe.course %>
</div>
<div class="show_description">
  <%= @recipe.description %>
</div>

<div>
  <%= image_tag(@recipe.picture_url,class:"recipe_image") if @recipe.picture.present? %>
</div>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>